Internal Server Error: /admin/auth/user/add/
Traceback (most recent call last):
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
AttributeError: module 'django.contrib.auth.password_validation' has no attribute 'UserUniqueValidator'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\auth\password_validation.py", line 29, in get_password_validators
    klass = import_string(validator["NAME"])
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\module_loading.py", line 32, in import_string
    raise ImportError(
    ...<2 lines>...
    ) from err
ImportError: Module "django.contrib.auth.password_validation" does not define a "UserUniqueValidator" attribute/class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    values = list(values)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\admin\helpers.py", line 158, in __iter__
    yield AdminField(self.form, field, is_first=(i == 0))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\admin\helpers.py", line 172, in __init__
    self.field = form[field]  # A django.forms.BoundField instance
                 ~~~~^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\forms\forms.py", line 185, in __getitem__
    self._bound_fields_cache[name] = field.get_bound_field(self, name)
                                     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\forms\fields.py", line 254, in get_bound_field
    return BoundField(form, self, field_name)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\forms\boundfield.py", line 27, in __init__
    self.help_text = field.help_text or ""
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\auth\password_validation.py", line 89, in _password_validators_help_text_html
    help_texts = password_validators_help_texts(password_validators)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\auth\password_validation.py", line 78, in password_validators_help_texts
    password_validators = get_default_password_validators()
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\auth\password_validation.py", line 22, in get_default_password_validators
    return get_password_validators(settings.AUTH_PASSWORD_VALIDATORS)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\auth\password_validation.py", line 35, in get_password_validators
    raise ImproperlyConfigured(msg % validator["NAME"])
django.core.exceptions.ImproperlyConfigured: The module in NAME could not be imported: django.contrib.auth.password_validation.UserUniqueValidator. Check your AUTH_PASSWORD_VALIDATORS setting.
"GET /admin/auth/user/add/ HTTP/1.1" 500 37418
Internal Server Error: /admin/auth/user/add/
Traceback (most recent call last):
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
AttributeError: module 'django.contrib.auth.password_validation' has no attribute 'UserUniqueValidator'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\auth\password_validation.py", line 29, in get_password_validators
    klass = import_string(validator["NAME"])
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\module_loading.py", line 32, in import_string
    raise ImportError(
    ...<2 lines>...
    ) from err
ImportError: Module "django.contrib.auth.password_validation" does not define a "UserUniqueValidator" attribute/class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    values = list(values)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\admin\helpers.py", line 158, in __iter__
    yield AdminField(self.form, field, is_first=(i == 0))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\admin\helpers.py", line 172, in __init__
    self.field = form[field]  # A django.forms.BoundField instance
                 ~~~~^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\forms\forms.py", line 185, in __getitem__
    self._bound_fields_cache[name] = field.get_bound_field(self, name)
                                     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\forms\fields.py", line 254, in get_bound_field
    return BoundField(form, self, field_name)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\forms\boundfield.py", line 27, in __init__
    self.help_text = field.help_text or ""
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\auth\password_validation.py", line 89, in _password_validators_help_text_html
    help_texts = password_validators_help_texts(password_validators)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\auth\password_validation.py", line 78, in password_validators_help_texts
    password_validators = get_default_password_validators()
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\auth\password_validation.py", line 22, in get_default_password_validators
    return get_password_validators(settings.AUTH_PASSWORD_VALIDATORS)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\auth\password_validation.py", line 35, in get_password_validators
    raise ImproperlyConfigured(msg % validator["NAME"])
django.core.exceptions.ImproperlyConfigured: The module in NAME could not be imported: django.contrib.auth.password_validation.UserUniqueValidator. Check your AUTH_PASSWORD_VALIDATORS setting.
"GET /admin/auth/user/add/ HTTP/1.1" 500 37399
Internal Server Error: /admin/appEmpresaLibros/libro/
Traceback (most recent call last):
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\admin\views\main.py", line 145, in __init__
    self.queryset = self.get_queryset(request)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\admin\views\main.py", line 583, in get_queryset
    qs, search_may_have_duplicates = self.model_admin.get_search_results(
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        request,
        ^^^^^^^^
        qs,
        ^^^
        self.query,
        ^^^^^^^^^^^
    )
    ^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\contrib\admin\options.py", line 1222, in get_search_results
    queryset = queryset.filter(models.Q.create(term_queries))
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\sql\query.py", line 1468, in build_filter
    return self._add_q(
           ~~~~~~~~~~~^
        filter_expr,
        ^^^^^^^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\sql\query.py", line 1468, in build_filter
    return self._add_q(
           ~~~~~~~~~~~^
        filter_expr,
        ^^^^^^^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\sql\query.py", line 1379, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\db\models\sql\query.py", line 1423, in try_transform
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Unsupported lookup 'icontains' for ForeignKey or join on the field not permitted.
"GET /admin/appEmpresaLibros/libro/?q=Harry HTTP/1.1" 500 18769
Internal Server Error: /es/appEmpresaLibros/
Traceback (most recent call last):
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\telmo\empresaLibros\appEmpresaLibros\views.py", line 16, in portada_view
    return render(request, 'portada.html', {'recientes_por_editorial': recientes_por_editorial})
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 563, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 9: 'trans', expected 'endblock'. Did you forget to register or load this tag?
"GET /es/appEmpresaLibros/ HTTP/1.1" 500 19079
Internal Server Error: /es/appEmpresaLibros/
Traceback (most recent call last):
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\telmo\empresaLibros\appEmpresaLibros\views.py", line 16, in portada_view
    return render(request, 'portada.html', {'recientes_por_editorial': recientes_por_editorial})
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
"GET /es/appEmpresaLibros/ HTTP/1.1" 500 16892
Internal Server Error: /es/appEmpresaLibros/
Traceback (most recent call last):
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\telmo\empresaLibros\appEmpresaLibros\views.py", line 16, in portada_view
    return render(request, 'portada.html', {'recientes_por_editorial': recientes_por_editorial})
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\telmo\Envs\empresaLibrosEnv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
"GET /es/appEmpresaLibros/ HTTP/1.1" 500 16842
Internal Server Error: /en/appEmpresaLibros/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: '='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 16, in portada_view
    return render(request, 'portada.html', {'recientes_por_editorial': recientes_por_editorial})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/smartif.py", line 182, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 706, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=' from '='
"GET /en/appEmpresaLibros/ HTTP/1.1" 500 21982
Internal Server Error: /it/appEmpresaLibros/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 16, in portada_view
    return render(request, 'portada.html', {'recientes_por_editorial': recientes_por_editorial})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
"GET /it/appEmpresaLibros/ HTTP/1.1" 500 16280
Internal Server Error: /it/appEmpresaLibros/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 16, in portada_view
    return render(request, 'portada.html', {'recientes_por_editorial': recientes_por_editorial})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
"GET /it/appEmpresaLibros/ HTTP/1.1" 500 16153
Internal Server Error: /it/appEmpresaLibros/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 16, in portada_view
    return render(request, 'portada.html', {'recientes_por_editorial': recientes_por_editorial})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
"GET /it/appEmpresaLibros/ HTTP/1.1" 500 16156
Internal Server Error: /it/appEmpresaLibros/libros/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 34, in libro_list_view
    return render(request, 'libro_list.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
"GET /it/appEmpresaLibros/libros/?search=isabel HTTP/1.1" 500 15921
Internal Server Error: /it/appEmpresaLibros/libros/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 34, in libro_list_view
    return render(request, 'libro_list.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
"GET /it/appEmpresaLibros/libros/?search=isabel HTTP/1.1" 500 15869
Internal Server Error: /it/appEmpresaLibros/libros/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 34, in libro_list_view
    return render(request, 'libro_list.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
"GET /it/appEmpresaLibros/libros/?search=isabel HTTP/1.1" 500 15863
Internal Server Error: /it/appEmpresaLibros/libro/2/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 47, in libro_detail_view
    return render(request, 'libro_detail.html', {'libro': libro})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 519, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 536, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends "base.html"> must be the first tag in the template.
"GET /it/appEmpresaLibros/libro/2/ HTTP/1.1" 500 17221
Internal Server Error: /it/appEmpresaLibros/libro/2/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 47, in libro_detail_view
    return render(request, 'libro_detail.html', {'libro': libro})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 519, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 536, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends "base.html"> must be the first tag in the template.
"GET /it/appEmpresaLibros/libro/2/ HTTP/1.1" 500 16950
Internal Server Error: /it/appEmpresaLibros/libro/2/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 47, in libro_detail_view
    return render(request, 'libro_detail.html', {'libro': libro})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 519, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 536, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends "base.html"> must be the first tag in the template.
"GET /it/appEmpresaLibros/libro/2/ HTTP/1.1" 500 16946
Internal Server Error: /it/appEmpresaLibros/libro/1/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 47, in libro_detail_view
    return render(request, 'libro_detail.html', {'libro': libro})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 519, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 536, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends "base.html"> must be the first tag in the template.
"GET /it/appEmpresaLibros/libro/1/ HTTP/1.1" 500 17019
Internal Server Error: /en/appEmpresaLibros/autor/1/
Traceback (most recent call last):
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/Documents/GitHub/empresaLibros/appEmpresaLibros/views.py", line 95, in autor_detail_view
    return render(request, 'autor_detail.html', {'autor': autor})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/templatetags/i18n.py", line 403, in do_translate
    message_string = parser.compile_filter(bits[1])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ikerariasmartinez/.virtualenvs/empresaLibrosEnv/lib/python3.12/site-packages/django/template/base.py", line 706, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':' from '"País":'
"GET /en/appEmpresaLibros/autor/1/ HTTP/1.1" 500 18369
